BEGIN TRANSACTION;
insert into country values('ABW', 'Aruba');
insert into country values('AFG', 'Afghanistan');
insert into country values('AGO', 'Angola');
insert into country values('AIA', 'Anguilla');
insert into country values('ALA', 'Aland Islands');
insert into country values('ALB', 'Albania');
insert into country values('AND', 'Andorra');
insert into country values('ARE', 'United Arab Emirates');
insert into country values('ARG', 'Argentina');
insert into country values('ARM', 'Armenia');
insert into country values('ASM', 'American Samoa');
insert into country values('ATA', 'Antarctica');
insert into country values('ATF', 'French Southern Territories');
insert into country values('ATG', 'Antigua and Barbuda');
insert into country values('AUS', 'Australia');
insert into country values('AUT', 'Austria');
insert into country values('AZE', 'Azerbaijan');
insert into country values('BDI', 'Burundi');
insert into country values('BEL', 'Belgium');
insert into country values('BEN', 'Benin');
insert into country values('BES', 'Bonaire, Sint Eustatius and Saba');
insert into country values('BFA', 'Burkina Faso');
insert into country values('BGD', 'Bangladesh');
insert into country values('BGR', 'Bulgaria');
insert into country values('BHR', 'Bahrain');
insert into country values('BHS', 'Bahamas');
insert into country values('BIH', 'Bosnia and Herzegovina');
insert into country values('BLM', 'Saint Barthélemy');
insert into country values('BLR', 'Belarus');
insert into country values('BLZ', 'Belize');
insert into country values('BMU', 'Bermuda');
insert into country values('BOL', 'Bolivia, Plurinational State of');
insert into country values('BRA', 'Brazil');
insert into country values('BRB', 'Barbados');
insert into country values('BRN', 'Brunei Darussalam');
insert into country values('BTN', 'Bhutan');
insert into country values('BVT', 'Bouvet Island');
insert into country values('BWA', 'Botswana');
insert into country values('CAF', 'Central African Republic');
insert into country values('CAN', 'Canada');
insert into country values('CCK', 'Cocos (Keeling) Islands');
insert into country values('CHE', 'Switzerland');
insert into country values('CHL', 'Chile');
insert into country values('CHN', 'China');
insert into country values('CIV', 'Côte d''Ivoire');
insert into country values('CMR', 'Cameroon');
insert into country values('COD', 'Congo, the Democratic Republic of the');
insert into country values('COG', 'Congo');
insert into country values('COK', 'Cook Islands');
insert into country values('COL', 'Colombia');
insert into country values('COM', 'Comoros');
insert into country values('CPV', 'Cabo Verde');
insert into country values('CRI', 'Costa Rica');
insert into country values('CUB', 'Cuba');
insert into country values('CUW', 'Curaçao');
insert into country values('CXR', 'Christmas Island');
insert into country values('CYM', 'Cayman Islands');
insert into country values('CYP', 'Cyprus');
insert into country values('CZE', 'Czech Republic');
insert into country values('DEU', 'Germany');
insert into country values('DJI', 'Djibouti');
insert into country values('DMA', 'Dominica');
insert into country values('DNK', 'Denmark');
insert into country values('DOM', 'Dominican Republic');
insert into country values('DZA', 'Algeria');
insert into country values('ECU', 'Ecuador');
insert into country values('EGY', 'Egypt');
insert into country values('ERI', 'Eritrea');
insert into country values('ESH', 'Western Sahara');
insert into country values('ESP', 'Spain');
insert into country values('EST', 'Estonia');
insert into country values('ETH', 'Ethiopia');
insert into country values('FIN', 'Finland');
insert into country values('FJI', 'Fiji');
insert into country values('FLK', 'Falkland Islands (Malvinas)');
insert into country values('FRA', 'France');
insert into country values('FRO', 'Faroe Islands');
insert into country values('FSM', 'Micronesia, Federated States of');
insert into country values('GAB', 'Gabon');
insert into country values('GBR', 'United Kingdom');
insert into country values('GEO', 'Georgia');
insert into country values('GGY', 'Guernsey');
insert into country values('GHA', 'Ghana');
insert into country values('GIB', 'Gibraltar');
insert into country values('GIN', 'Guinea');
insert into country values('GLP', 'Guadeloupe');
insert into country values('GMB', 'Gambia');
insert into country values('GNB', 'Guinea-Bissau');
insert into country values('GNQ', 'Equatorial Guinea');
insert into country values('GRC', 'Greece');
insert into country values('GRD', 'Grenada');
insert into country values('GRL', 'Greenland');
insert into country values('GTM', 'Guatemala');
insert into country values('GUF', 'French Guiana');
insert into country values('GUM', 'Guam');
insert into country values('GUY', 'Guyana');
insert into country values('HKG', 'Hong Kong');
insert into country values('HMD', 'Heard Island and McDonald Islands');
insert into country values('HND', 'Honduras');
insert into country values('HRV', 'Croatia');
insert into country values('HTI', 'Haiti');
insert into country values('HUN', 'Hungary');
insert into country values('IDN', 'Indonesia');
insert into country values('IMN', 'Isle of Man');
insert into country values('IND', 'India');
insert into country values('IOT', 'British Indian Ocean Territory');
insert into country values('IRL', 'Ireland');
insert into country values('IRN', 'Iran, Islamic Republic of');
insert into country values('IRQ', 'Iraq');
insert into country values('ISL', 'Iceland');
insert into country values('ISR', 'Israel');
insert into country values('ITA', 'Italy');
insert into country values('JAM', 'Jamaica');
insert into country values('JEY', 'Jersey');
insert into country values('JOR', 'Jordan');
insert into country values('JPN', 'Japan');
insert into country values('KAZ', 'Kazakhstan');
insert into country values('KEN', 'Kenya');
insert into country values('KGZ', 'Kyrgyzstan');
insert into country values('KHM', 'Cambodia');
insert into country values('KIR', 'Kiribati');
insert into country values('KNA', 'Saint Kitts and Nevis');
insert into country values('KOR', 'Korea, Republic of');
insert into country values('KWT', 'Kuwait');
insert into country values('LAO', 'Lao People''s Democratic Republic');
insert into country values('LBN', 'Lebanon');
insert into country values('LBR', 'Liberia');
insert into country values('LBY', 'Libya');
insert into country values('LCA', 'Saint Lucia');
insert into country values('LIE', 'Liechtenstein');
insert into country values('LKA', 'Sri Lanka');
insert into country values('LSO', 'Lesotho');
insert into country values('LTU', 'Lithuania');
insert into country values('LUX', 'Luxembourg');
insert into country values('LVA', 'Latvia');
insert into country values('MAC', 'Macao');
insert into country values('MAF', 'Saint Martin (French part)');
insert into country values('MAR', 'Morocco');
insert into country values('MCO', 'Monaco');
insert into country values('MDA', 'Moldova, Republic of');
insert into country values('MDG', 'Madagascar');
insert into country values('MDV', 'Maldives');
insert into country values('MEX', 'Mexico');
insert into country values('MHL', 'Marshall Islands');
insert into country values('MKD', 'Macedonia, the former Yugoslav Republic of');
insert into country values('MLI', 'Mali');
insert into country values('MLT', 'Malta');
insert into country values('MMR', 'Myanmar');
insert into country values('MNE', 'Montenegro');
insert into country values('MNG', 'Mongolia');
insert into country values('MNP', 'Northern Mariana Islands');
insert into country values('MOZ', 'Mozambique');
insert into country values('MRT', 'Mauritania');
insert into country values('MSR', 'Montserrat');
insert into country values('MTQ', 'Martinique');
insert into country values('MUS', 'Mauritius');
insert into country values('MWI', 'Malawi');
insert into country values('MYS', 'Malaysia');
insert into country values('MYT', 'Mayotte');
insert into country values('NAM', 'Namibia');
insert into country values('NCL', 'New Caledonia');
insert into country values('NER', 'Niger');
insert into country values('NFK', 'Norfolk Island');
insert into country values('NGA', 'Nigeria');
insert into country values('NIC', 'Nicaragua');
insert into country values('NIU', 'Niue');
insert into country values('NLD', 'Netherlands');
insert into country values('NOR', 'Norway');
insert into country values('NPL', 'Nepal');
insert into country values('NRU', 'Nauru');
insert into country values('NZL', 'New Zealand');
insert into country values('OMN', 'Oman');
insert into country values('PAK', 'Pakistan');
insert into country values('PAN', 'Panama');
insert into country values('PCN', 'Pitcairn');
insert into country values('PER', 'Peru');
insert into country values('PHL', 'Philippines');
insert into country values('PLW', 'Palau');
insert into country values('PNG', 'Papua New Guinea');
insert into country values('POL', 'Poland');
insert into country values('PRI', 'Puerto Rico');
insert into country values('PRK', 'Korea, Democratic People''s Republic of');
insert into country values('PRT', 'Portugal');
insert into country values('PRY', 'Paraguay');
insert into country values('PSE', 'Palestine, State of');
insert into country values('PYF', 'French Polynesia');
insert into country values('QAT', 'Qatar');
insert into country values('REU', 'Réunion');
insert into country values('ROU', 'Romania');
insert into country values('RUS', 'Russian Federation');
insert into country values('RWA', 'Rwanda');
insert into country values('SAU', 'Saudi Arabia');
insert into country values('SDN', 'Sudan');
insert into country values('SEN', 'Senegal');
insert into country values('SGP', 'Singapore');
insert into country values('SGS', 'South Georgia and the South Sandwich Islands');
insert into country values('SHN', 'Saint Helena, Ascension and Tristan da Cunha');
insert into country values('SJM', 'Svalbard and Jan Mayen');
insert into country values('SLB', 'Solomon Islands');
insert into country values('SLE', 'Sierra Leone');
insert into country values('SLV', 'El Salvador');
insert into country values('SMR', 'San Marino');
insert into country values('SOM', 'Somalia');
insert into country values('SPM', 'Saint Pierre and Miquelon');
insert into country values('SRB', 'Serbia');
insert into country values('SSD', 'South Sudan');
insert into country values('STP', 'Sao Tome and Principe');
insert into country values('SUR', 'Suriname');
insert into country values('SVK', 'Slovakia');
insert into country values('SVN', 'Slovenia');
insert into country values('SWE', 'Sweden');
insert into country values('SWZ', 'Swaziland');
insert into country values('SXM', 'Sint Maarten (Dutch part)');
insert into country values('SYC', 'Seychelles');
insert into country values('SYR', 'Syrian Arab Republic');
insert into country values('TCA', 'Turks and Caicos Islands');
insert into country values('TCD', 'Chad');
insert into country values('TGO', 'Togo');
insert into country values('THA', 'Thailand');
insert into country values('TJK', 'Tajikistan');
insert into country values('TKL', 'Tokelau');
insert into country values('TKM', 'Turkmenistan');
insert into country values('TLS', 'Timor-Leste');
insert into country values('TON', 'Tonga');
insert into country values('TTO', 'Trinidad and Tobago');
insert into country values('TUN', 'Tunisia');
insert into country values('TUR', 'Turkey');
insert into country values('TUV', 'Tuvalu');
insert into country values('TWN', 'Taiwan, Province of China');
insert into country values('TZA', 'Tanzania, United Republic of');
insert into country values('UGA', 'Uganda');
insert into country values('UKR', 'Ukraine');
insert into country values('UMI', 'United States Minor Outlying Islands');
insert into country values('URY', 'Uruguay');
insert into country values('USA', 'United States of America');
insert into country values('UZB', 'Uzbekistan');
insert into country values('VAT', 'Holy See (Vatican City State)');
insert into country values('VCT', 'Saint Vincent and the Grenadines');
insert into country values('VEN', 'Venezuela, Bolivarian Republic of');
insert into country values('VGB', 'Virgin Islands, British');
insert into country values('VIR', 'Virgin Islands, U.S.');
insert into country values('VNM', 'Viet Nam');
insert into country values('VUT', 'Vanuatu');
insert into country values('WLF', 'Wallis and Futuna');
insert into country values('WSM', 'Samoa');
insert into country values('YEM', 'Yemen');
insert into country values('ZAF', 'South Africa');
insert into country values('ZMB', 'Zambia');
insert into country values('ZWE', 'Zimbabwe');
END TRANSACTION;